headers: 
  appId: 
    description: Authentication header parameters
  appKey: 
    description: Authentication header parameters
queryParameters: 
  appId: 
    description: Authentication query parameters
  appKey: 
    description: Authentication query parameters
